package beans;
// Generated Dec 22, 2020 11:29:41 PM by Hibernate Tools 4.3.1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

    private int idCategory;
    private String categoryName;
    private String descrption;

    public Category() {
    }

    public Category(int idCategory, String descrption) {
        this.idCategory = idCategory;
        this.descrption = descrption;
    }

    public int getIdCategory() {
        return this.idCategory;
    }

    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getDescrption() {
        return this.descrption;
    }

    public void setDescrption(String descrption) {
        this.descrption = descrption;
    }

}
