package beans;
// Generated Dec 22, 2020 11:29:41 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

    private int itemId;
    private Category category;
    private String productCode;
    private String itemName;
    private String itemDescription;
    private BigDecimal itemPrice;
    private BigDecimal actualPrice;
    private BigDecimal discount;
    private String dateCreated;
    private boolean availability;
    private String imageItem;
    private boolean delivery;
    private String deliveryTimePeriod;
    private boolean warranty;
    private String warrantyPeriod;
    private String lastUpdated;

    public Item() {
    }

    public Item(int itemId, Category category, String itemName, String itemDescription, BigDecimal itemPrice, BigDecimal actualPrice, BigDecimal discount, String dateCreated, boolean availability, String imageItem, boolean delivery, String deliveryTimePeriod, boolean warranty, String warrantyPeriod, String lastUpdated) {
        this.itemId = itemId;
        this.category = category;
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.itemPrice = itemPrice;
        this.actualPrice = actualPrice;
        this.discount = discount;
        this.dateCreated = dateCreated;
        this.availability = availability;
        this.imageItem = imageItem;
        this.delivery = delivery;
        this.deliveryTimePeriod = deliveryTimePeriod;
        this.warranty = warranty;
        this.warrantyPeriod = warrantyPeriod;
        this.lastUpdated = lastUpdated;
    }

    public Item(int itemId, Category category, String productCode, String itemName, String itemDescription, BigDecimal itemPrice, BigDecimal actualPrice, BigDecimal discount, String dateCreated, boolean availability, String imageItem, boolean delivery, String deliveryTimePeriod, boolean warranty, String warrantyPeriod, String lastUpdated) {
        this.itemId = itemId;
        this.category = category;
        this.productCode = productCode;
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.itemPrice = itemPrice;
        this.actualPrice = actualPrice;
        this.discount = discount;
        this.dateCreated = dateCreated;
        this.availability = availability;
        this.imageItem = imageItem;
        this.delivery = delivery;
        this.deliveryTimePeriod = deliveryTimePeriod;
        this.warranty = warranty;
        this.warrantyPeriod = warrantyPeriod;
        this.lastUpdated = lastUpdated;
    }

    public int getItemId() {
        return this.itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public BigDecimal getItemPrice() {
        return this.itemPrice;
    }

    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    public BigDecimal getActualPrice() {
        return this.actualPrice;
    }

    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public boolean getAvailability() {
        return this.availability;
    }

    public void setAvailability(boolean availability) {
        this.availability = availability;
    }

    public String getImageItem() {
        return this.imageItem;
    }

    public void setImageItem(String imageItem) {
        this.imageItem = imageItem;
    }

    public boolean getDelivery() {
        return this.delivery;
    }

    public void setDelivery(boolean delivery) {
        this.delivery = delivery;
    }

    public String getDeliveryTimePeriod() {
        return this.deliveryTimePeriod;
    }

    public void setDeliveryTimePeriod(String deliveryTimePeriod) {
        this.deliveryTimePeriod = deliveryTimePeriod;
    }

    public boolean getWarranty() {
        return this.warranty;
    }

    public void setWarranty(boolean warranty) {
        this.warranty = warranty;
    }

    public String getWarrantyPeriod() {
        return this.warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    public String getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
