package beans;
// Generated Dec 22, 2020 11:29:41 PM by Hibernate Tools 4.3.1

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

    private int idUserRole;
    private Role role;
    private User user;

    public UserRole() {
    }

    public UserRole(int idUserRole, Role role, User user) {
        this.idUserRole = idUserRole;
        this.role = role;
        this.user = user;
    }

    public int getIdUserRole() {
        return this.idUserRole;
    }

    public void setIdUserRole(int idUserRole) {
        this.idUserRole = idUserRole;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
