package beans;
// Generated Dec 22, 2020 11:29:41 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int idUser;
    private String password;
    private String firstName;
    private String lastName;
    private String salt;
    private String email;
    private String dateCreated;
    private String lastUpdated;

    public User() {
    }

    public User(int idUser, String password, String firstName, String lastName, String salt, String email, String dateCreated, String lastUpdated) {
        this.idUser = idUser;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.salt = salt;
        this.email = email;
        this.dateCreated = dateCreated;
        this.lastUpdated = lastUpdated;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
